version: '3.8'

services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.16.5"  # Specify the version
      ONLINE_MODE: "FALSE"  # Allow cracked clients
    volumes:
      - minecraft_data:/data  # Persist data

volumes:
  minecraft_data:
